"""Tests for CrossEncoderScorer (#187 rerank model-wire).

The empty-docs short-circuit and the protocol-integration with
``reranker_gate.rerank_candidates`` are model-free (no load). The real ONNX
load + rank is gated on the model being present in the local HF cache, so it
runs as a receipt on a dev box but SKIPS in a clean-cache CI (no forced download,
no HF-429 flake). CI real-model coverage arrives once the model is baked.
"""

from __future__ import annotations

import importlib.util

import pytest

from src.cross_encoder_scorer import DEFAULT_RERANK_MODEL, CrossEncoderScorer


def test_empty_documents_returns_empty_without_loading():
    scorer = CrossEncoderScorer()
    assert scorer("a query", []) == []
    assert scorer.is_loaded is False  # the empty path must not trigger a model load


def test_usable_as_injected_scorer_when_rerank_disabled_no_load():
    # Structural contract: a CrossEncoderScorer is a valid RerankScorer for
    # rerank_candidates. With rerank disabled it is never invoked -> no load.
    from src.reranker_gate import RerankConfig, rerank_candidates

    scorer = CrossEncoderScorer()
    candidates = [("a", 1.0), ("b", 0.5)]
    out, did_rerank = rerank_candidates(
        "q",
        candidates,
        text_of=lambda c: c[0],
        score_of=lambda c: c[1],
        scorer=scorer,
        config=RerankConfig(enabled=False),
    )
    assert did_rerank is False
    assert out == candidates
    assert scorer.is_loaded is False


def _model_cached() -> bool:
    """True if the default cross-encoder is already in the local HF cache.

    codex round-3 finding 2: ``try_to_load_from_cache`` can return a truthy,
    non-None SENTINEL (``huggingface_hub.file_download._CACHED_NO_EXIST``)
    meaning "the hub already recorded that this file does not exist on this
    repo" -- not a real path. A bare ``is not None`` check accepts that
    sentinel as if it were usable, which would let this skip guard read as
    "cached" and push the slow real-model test into a live download instead
    of skipping cleanly. Guard with an isinstance(str) check first (the
    sentinel is not a string) and then verify the resolved path is an actual
    file on disk.
    """
    if importlib.util.find_spec("optimum") is None:
        return False
    try:
        from pathlib import Path

        from huggingface_hub import try_to_load_from_cache

        resolved = try_to_load_from_cache(DEFAULT_RERANK_MODEL, "config.json")
        return isinstance(resolved, str) and Path(resolved).is_file()
    except Exception:
        return False


@pytest.mark.slow
@pytest.mark.skipif(
    not _model_cached(),
    reason="cross-encoder model not in local HF cache; skip download in clean-cache CI",
)
def test_real_onnx_cross_encoder_ranks_relevant_above_irrelevant():
    scorer = CrossEncoderScorer()
    query = "how to configure custom colors in the tailwind theme"
    docs = [
        "drizzle-kit migrate applies SQL migrations generated by drizzle-kit generate.",
        "Override any of the default colors by defining new theme variables inside @theme.",
    ]
    try:
        scores = scorer(query, docs)
    except Exception as exc:  # pragma: no cover - cache/model unavailable in this env
        pytest.skip(f"cross-encoder model unavailable at runtime: {exc}")
    assert len(scores) == 2
    assert scorer.is_loaded is True
    assert all(isinstance(s, float) for s in scores)
    # idx 1 is on-topic (tailwind theme colors); idx 0 is unrelated (drizzle).
    assert scores[1] > scores[0]
